# Generated by Django 4.0.1 on 2022-06-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField()),
                ('nombreProducto', models.TextField(max_length=100)),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
            ],
        ),
    ]
