# Generated by Django 4.0.1 on 2022-06-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoPago', models.IntegerField()),
                ('nombreTipoPago', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
