# Generated by Django 4.0.1 on 2022-06-28 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_usuario_is_active_alter_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
