# Generated by Django 4.0.1 on 2022-06-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoUsuario', models.TextField()),
            ],
        ),
    ]
