# Generated by Django 4.0.1 on 2022-06-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_tipousuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField()),
                ('nombreProducto', models.TextField(max_length=100)),
                ('categoriaProducto', models.IntegerField()),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
                ('precioCosto', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
