# Generated by Django 4.0.1 on 2022-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.TextField(max_length=50),
        ),
    ]
