# Generated by Django 4.0.1 on 2022-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_producto_categoriaproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=10)),
                ('dv', models.TextField(max_length=1)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('fechaNac', models.DateField()),
                ('password', models.TextField()),
                ('email', models.TextField(max_length=30)),
                ('direccion', models.TextField(max_length=30)),
                ('telefono', models.TextField(max_length=12)),
                ('tipoUsuario', models.TextField(max_length=20)),
            ],
        ),
    ]
