# Generated by Django 4.0.1 on 2022-06-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUsuario',
            new_name='tipoDeUsuario',
        ),
    ]
