# Generated by Django 4.0.1 on 2022-06-14 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
