# Generated by Django 4.0.1 on 2022-06-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_producto_descripcionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
