# Generated by Django 4.0.1 on 2022-06-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_delete_activecategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donacion', models.IntegerField()),
                ('nombreDonante', models.TextField(max_length=20)),
                ('tipoPago', models.IntegerField()),
            ],
        ),
    ]
