# Generated by Django 4.0.1 on 2022-06-28 05:45

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donacion', models.IntegerField()),
                ('nombreDonante', models.TextField(max_length=20)),
                ('tipoPago', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.TextField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.IntegerField()),
                ('nombreProducto', models.TextField(max_length=100)),
                ('descripcionProducto', models.TextField()),
                ('categoriaProducto', models.IntegerField()),
                ('marcaProducto', models.IntegerField()),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
                ('precioCosto', models.IntegerField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoPago', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoUsuario', models.TextField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=10)),
                ('dv', models.TextField(max_length=1)),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('fechaNac', models.DateField()),
                ('password', models.TextField()),
                ('email', models.TextField(max_length=30)),
                ('direccion', models.TextField(max_length=30)),
                ('telefono', models.TextField(max_length=12)),
                ('tipoDeUsuario', models.IntegerField()),
                ('last_login', models.DateField()),
                ('is_superuser', models.BooleanField()),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateField()),
                ('username', models.TextField(max_length=20, unique=True)),
                ('suscrito', models.BooleanField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
