# Generated by Django 4.0.1 on 2022-06-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_tipopago_delete_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopago',
            name='idTipoPago',
        ),
    ]
