# Generated by Django 4.0.1 on 2022-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_tipopago_idtipopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(max_length=100)),
                ('activo', models.BooleanField()),
            ],
        ),
    ]
