# Generated by Django 4.0.1 on 2022-06-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='activo',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
