# Generated by Django 4.0.1 on 2022-06-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_rename_tipousuario_usuario_tipodeusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMarca', models.TextField(max_length=50)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='marcaProducto',
            field=models.TextField(default='Dam Garden', max_length=20),
            preserve_default=False,
        ),
    ]
