# Generated by Django 4.0.1 on 2022-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_marca_producto_marcaproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoriaProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marcaProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoDeUsuario',
            field=models.IntegerField(),
        ),
    ]
