# Generated by Django 4.0.1 on 2022-06-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_activecategories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveCategories',
        ),
    ]
