# Generated by Django 4.0.1 on 2022-06-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0018_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suscrito',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
